### ISSUE TITLE
Error starting exporter

### ISSUE THREAD

**Issue by Seitanas** [liamcottle/sungrow-eyem4-exporter#1]
Hello, I'm having trouble starting exporter.
Seems to give the same error either if i specify `serve` or `help` command:

```
npx @liamcottle/sungrow-eyem4-exporter@latest help
/opt/sungrow/.npm/_npx/eec1b6416790189f/node_modules/@liamcottle/sungrow-eyem4-api/src/index.js:43
            const serviceName = json?.result_data?.service;
                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/sungrow/.npm/_npx/eec1b6416790189f/node_modules/@liamcottle/sungrow-eyem4-exporter/src/index.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /opt/sungrow
npm ERR! command failed
npm ERR! command sh -c sungrow-eyem4-exporter "help"

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/sungrow/.npm/_logs/2024-03-29T12_52_12_908Z-debug.log
```

Need to mention, that I'm trying to run this on raspberry (ARM).
Any ideas, what's wrong?
Thank you.

**Comment by liamcottle** [comment]
Hi, your NodeJS version is probably too old to handle nullsafe code. Try updating to latest version, or at least v18 and let me know if it works.

**Comment by Seitanas** [comment]
Hello, indeed upgrading seem to help.
Though now i'm getting `{"message":"Error: Unexpected server response: 400"}` error. Will have to investigate further.
Thank you.
